id: IF708A888
legacy_id: P009543
ocr_import_info:
  bdrc_scan_id: W1KG8836
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T21:46:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:05:25.306185+00:00'
last_modified: 2022-09-01 02:05:36.349406
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG8836
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG8836
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུས་དང་མཐའ་རྣམ་པར་འབྱེད་པའི་འགྲེལ་པ་སོགས་རྒྱ་གཞུང་གི་བསྟན་བཅོས་ཁག་ཅིག
  author: སློབ་དཔོན་ཐོགས་མེད།
statistics:
  ocr_word_mean_confidence_index: 0.6314744580687248
  ocr_word_median_confidence_index: 0.6600000262260437
quality: null
bases:
  I1KG8877:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8877
      total_pages: 370
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG8877.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6314744580687248
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
