id: P009543
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG8836
  title: དབུས་དང་མཐའ་རྣམ་པར་འབྱེད་པའི་འགྲེལ་པ་སོགས་རྒྱ་གཞུང་གི་བསྟན་བཅོས་ཁག་ཅིག
  author: ''
  volumes:
    6875daf6da71407d9e22f34e1080d7e0:
      image_group_id: I1KG8877
      title: ''
      volume_number: 1
      total_pages: 370
